/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Auth: () => import('#controllers/auth_controller'),
  AuthV2: () => import('#controllers/auth_v2_controller'),
  UserSettings: () => import('#controllers/user_settings_controller'),
  Webs: () => import('#controllers/webs_controller'),
}
