import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  protected tableName = 'billing_payments'

  async up() {
    this.schema.createTable(this.tableName, (table) => {
      table.uuid('id').primary()

      table
        .uuid('billing_id')
        .notNullable()
        .references('id')
        .inTable('billings')
        .onDelete('CASCADE')
        .index()

      /**
       * Payment gateway/provider.
       *
       * Examples:
       * - paystack
       * - hubtel
       * - flutterwave
       * - manual
       */
      table.string('gateway', 50).notNullable().index()

      /**
       * Internal payment reference generated by ScholarSaaS.
       *
       * Used to identify the payment during initialization,
       * webhook processing, and reconciliation.
       */
      table.string('reference', 50).notNullable().unique()

      /**
       * Provider/gateway transaction identifier.
       */
      table.string('transaction_id', 100).nullable().index()

      /**
       * Payment amount in the smallest currency unit.
       */
      table.integer('amount').notNullable().comment('in subunits of currency')

      table.string('currency', 10).notNullable().defaultTo('GHS')

      /**
       * pending    = payment initialized
       * processing = gateway/webhook processing
       * success    = payment confirmed
       * failed     = payment failed
       * cancelled  = payment cancelled
       * refunded   = payment refunded
       */
      table.string('status', 50).notNullable().defaultTo('pending').index()

      /**
       * Payment method/channel.
       *
       * Examples:
       * - card
       * - mobile_money
       * - bank_transfer
       * - cash
       */
      table.string('payment_method', 50).nullable().index()

      table.timestamp('paid_at').nullable()
      table.timestamp('verified_at').nullable()
      table.timestamp('failed_at').nullable()
      table.timestamp('refunded_at').nullable()

      /**
       * Gateway response metadata.
       *
       * Store only fields needed for verification,
       * reconciliation, debugging, and audit.
       */
      table.json('gateway_response').nullable()

      table.json('meta').nullable()

      table
        .uuid('paid_by_user_id')
        .nullable()
        .references('user_id')
        .inTable('users')
        .onDelete('SET NULL')
        .index()

      table.timestamp('created_at')
      table.timestamp('updated_at')

      table.index(['billing_id', 'status'])
      table.index(['gateway', 'reference'], 's_saas_billing_gateway_ref_index')
      table.index(['status', 'paid_at'])
    })
  }

  async down() {
    this.schema.dropTable(this.tableName)
  }
}
